npmScopes:
  glcap:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'
    npmPublishRegistry: 'https://npm.pkg.github.com/glcap'
    npmRegistryServer: 'https://npm.pkg.github.com/glcap'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.4.0.cjs
