name: Build & Publish to Github Packages

on:
  push:
    tags:
      - '*'
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build source
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Publish to Github Package Registry
        run: yarn npm publish
